### ISSUE TITLE
Evaluasi Task 2

### ISSUE THREAD

**Issue by aufaroot18** [rafifmulia/nffrontend01#1]
- Gunakan for of untuk looping array

**Comment by rafifmulia** [comment]
Iya bisa juga pake for, tapi untuk di task ini instruksinya pake .find, .map, .filter bukannya ka ? apa ini hanya saran aja kah ? hehe..

**Comment by aufaroot18** [comment]
ini tugas 2, bukan tugas 3 kan? yang di fungsi `all` pada tugas 2.

kalo tugas 3 baru make map, find, dan filter.

kalo looping array itu make `for of`, kalo `for in` itu untuk looping object.

`users` itu kan array, jadi make `for of` untuk looping-nya.

**Comment by rafifmulia** [comment]
oh ini tugas pertemuan 3 ka, sory kalo penamaan branchnya bingung
kalo tugas pertemuan 2 itu di branch task01
yang tugas baru2 ini pertemuan 04 itu nama branchnya pertemuan04

**Comment by aufaroot18** [comment]
okeey nice, siap gpp.
